name: Daily Reading Scraping

on:
  schedule:
    - cron: "35 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Add content roots to PYTHONPATH
#        env:
#          PYTHONPATH: ${{ github.workspace }}/services
#        run: |
#          echo "export PYTHONPATH=${PYTHONPATH}" >> $GITHUB_ENV
      
      - name: Run scraper
        env: 
          UPSTACK_CONNECTION_STR: ${{ secrets.UPSTACK_CONNECTION_STR }}
          UPSTACK_ENDPOINT: ${{ secrets.UPSTACK_ENDPOINT }}
          UPSTACK_PORT: ${{ secrets.UPSTACK_PORT }}
          UPSTACK_PASSWORD: ${{ secrets.UPSTACK_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python lectura.py 